doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Authentication:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Authentication/Domain/User/Entity'
                prefix: 'App\Authentication\Domain\User\Entity'
                alias: Authentication
            App\Tasks:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Tasks/Domain/Task/Entity'
                prefix: 'App\Tasks\Domain\Task\Entity'
                alias: Tasks